name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/chisom-pem.pem
        chmod 600 ~/.ssh/chisom-pem.pem

    - name: Deploy to EC2
      run: |   
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/chisom-pem.pem ubuntu@${{ secrets.EC2_PUBLIC_KEY }} << 'EOF'
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi-book-project.service
        EOF